-- ALTER TABLE PARTICIPE ALTER COLUMN idParticipant INT NOT NULL;
-- ALTER TABLE PARTICIPE ALTER COLUMN idAnimation INT NOT NULL;

-- ALTER TABLE PARTICIPE ADD PRIMARY KEY (idAnimation, idParticipant)

-- ALTER TABLE PARTICIPE ADD FOREIGN KEY (idParticipant) REFERENCES PARTICIPANT(idParticipant);
-- ALTER TABLE PARTICIPE ADD FOREIGN KEY (idAnimation) REFERENCES ANIMATION(idAnimation);

-- INSERT INTO ANIMATEUR VALUES (1,'Martin','Mike',18)
-- INSERT INTO ANIMATEUR VALUES (2,'William','Joe',32)
-- INSERT INTO ANIMATEUR VALUES (3,'Buck','Bill',19)
-- INSERT INTO ANIMATEUR VALUES (4,'Dario','Albert',25)
-- INSERT INTO ANIMATEUR VALUES (5,'Mora','Peter',29)

-- INSERT INTO STAND VALUES(111,20)
-- INSERT INTO STAND VALUES(222,50)
-- INSERT INTO STAND VALUES(333,30)
-- INSERT INTO STAND VALUES(444,100)

-- INSERT INTO ENTREPRISE VALUES (10,'Microsoft','Paris',500)
-- INSERT INTO ENTREPRISE VALUES (20,'Apple','Limoges',200)
-- INSERT INTO ENTREPRISE VALUES (30,'Mécano','Paris',15)

-- INSERT INTO PARTICIPANT VALUES (1,'Toto','Limoges',10)
-- INSERT INTO PARTICIPANT VALUES (2,'Tata','Paris',10)
-- INSERT INTO PARTICIPANT VALUES (3,'Titi','Limoges',10)
-- INSERT INTO PARTICIPANT VALUES (4,'Tutu','Paris',10)
-- INSERT INTO PARTICIPANT VALUES (5,'Tato','Limoges',20)
-- INSERT INTO PARTICIPANT VALUES (6,'Tatu','Paris',20)
-- INSERT INTO PARTICIPANT VALUES (7,'Tito','Limoges',20)
-- INSERT INTO PARTICIPANT VALUES (8,'Toti','Limoges',30)
-- INSERT INTO PARTICIPANT VALUES (9,'Tota','Limoges',30)

-- INSERT INTO ANIMATION VALUES (1,111,2,'Forum','17/12/2020','07:59:00')
-- INSERT INTO ANIMATION VALUES (2,222,3,'JPO','31/12/2021','18:30:00')
-- INSERT INTO ANIMATION VALUES (3,444,5,'Rien','31/12/2021','12:30:00')
-- INSERT INTO ANIMATION VALUES (4,111,2,'Forum','17/12/2021','07:50:00')
-- INSERT INTO ANIMATION VALUES (5,111,3,'Forum','17/11/2021','18:54:00')

-- INSERT INTO PARTICIPE VALUES(1,1)
-- INSERT INTO PARTICIPE VALUES(1,2)
-- INSERT INTO PARTICIPE VALUES(1,3)
-- INSERT INTO PARTICIPE VALUES(1,4) 
-- INSERT INTO PARTICIPE VALUES(1,5)
-- INSERT INTO PARTICIPE VALUES(2,6)
-- INSERT INTO PARTICIPE VALUES(2,7)
-- INSERT INTO PARTICIPE VALUES(2,1)
-- INSERT INTO PARTICIPE VALUES(2,2)
-- INSERT INTO PARTICIPE VALUES(3,2)
-- INSERT INTO PARTICIPE VALUES(3,4)
-- INSERT INTO PARTICIPE VALUES(3,8)

-- SELECT nom, prenom FROM ANIMATEUR
-- WHERE age < 25

-- SELECT idStand FROM STAND
-- ORDER BY idStand DESC

-- SELECT idAnimation, titre FROM ANIMATION
-- WHERE dateAnimation = '31-12-2021' AND
-- heure >= '12:00:00' AND heure <= '19:00:00'

-- SELECT PARTICIPANT.nom FROM PARTICIPANT, ENTREPRISE, PARTICIPE
-- WHERE PARTICIPE.idParticipant = PARTICIPANT.idParticipant 
-- AND PARTICIPANT.idEntreprise = ENTREPRISE.idEntreprise
-- AND ENTREPRISE.nom = 'Mécano'

-- SELECT COUNT(PARTICIPANT.nom) as count FROM PARTICIPANT, ANIMATION, PARTICIPE
-- WHERE PARTICIPE.idParticipant = PARTICIPANT.idParticipant 
-- AND PARTICIPE.idAnimation = ANIMATION.idAnimation
-- AND ANIMATION.titre = 'JPO'

-- SELECT COUNT(DISTINCT ANIMATEUR.idAnimateur) as count FROM ANIMATEUR, ANIMATION
-- WHERE ANIMATION.idAnimateur = ANIMATEUR.idAnimateur 
-- AND ANIMATION.titre = 'FORUM'

-- SELECT DISTINCT STAND.idStand FROM STAND, ANIMATION
-- WHERE STAND.idStand = ANIMATION.idStand 
-- AND YEAR(ANIMATION.dateAnimation) = '2021'

-- SELECT SUM(count) as Total FROM (
-- (SELECT COUNT(DISTINCT PARTICIPANT.nom) as count FROM PARTICIPANT, ANIMATION, PARTICIPE
-- WHERE PARTICIPE.idParticipant = PARTICIPANT.idParticipant 
-- AND PARTICIPE.idAnimation = ANIMATION.idAnimation
-- AND YEAR(ANIMATION.dateAnimation) = '2021')
-- UNION
-- (SELECT COUNT(DISTINCT ANIMATEUR.idAnimateur) as count FROM ANIMATEUR, ANIMATION
-- WHERE ANIMATION.idAnimateur = ANIMATEUR.idAnimateur 
-- AND YEAR(ANIMATION.dateAnimation) = '2021')) MAISWHAT

-- SELECT PARTICIPANT.nom FROM PARTICIPANT, ANIMATION, PARTICIPE
-- WHERE PARTICIPE.idParticipant = PARTICIPANT.idParticipant 
-- AND PARTICIPE.idAnimation = ANIMATION.idAnimation
-- AND ANIMATION.titre = 'JPO'
-- INTERSECT
-- SELECT PARTICIPANT.nom FROM PARTICIPANT, ANIMATION, PARTICIPE
-- WHERE PARTICIPE.idParticipant = PARTICIPANT.idParticipant 
-- AND PARTICIPE.idAnimation = ANIMATION.idAnimation
-- AND ANIMATION.titre = 'Forum'

-- SELECT nom FROM ANIMATEUR
-- EXCEPT (
-- SELECT DISTINCT nom FROM ANIMATEUR, ANIMATION
-- WHERE ANIMATION.idAnimateur = ANIMATEUR.idAnimateur
-- AND heure > '18:00:00')

-- SELECT nom FROM ANIMATEUR
-- WHERE idAnimateur IN (
--     SELECT idAnimateur FROM ANIMATION GROUP BY idAnimateur HAVING COUNT(idAnimateur) > 1
-- )

-- SELECT nom FROM ENTREPRISE
-- WHERE idEntreprise IN (
--     SELECT ENTREPRISE.idEntreprise FROM ENTREPRISE, PARTICIPE, PARTICIPANT
--     WHERE PARTICIPE.idParticipant = PARTICIPANT.idParticipant
--     AND ENTREPRISE.idEntreprise = PARTICIPANT.idEntreprise
--     GROUP BY ENTREPRISE.idEntreprise
--     HAVING COUNT(ENTREPRISE.idEntreprise) > 3
-- )

